#sample scenarios to be tested:
#@author Kaan Tural, Nicholas O'Sullivan
### unauthorized register, return error
GET localhost:8080/api/v1/register

### Register team5
GET localhost:8080/api/v1/register
Authorization: Basic VGVhbTU6NXBhc3N3b3Jk



### GetPublishers w/ team5 registered
GET localhost:8080/api/v1/getPublishers
Authorization: Basic VGVhbTU6NXBhc3N3b3Jk
###

### Register Mike
GET localhost:8080/api/v1/register
Authorization: Basic TWlrZToxMjM0NXBhc3N3b3Jk
###

### GetPublishers w/ team5 & mike register
GET localhost:8080/api/v1/getPublishers
Authorization: Basic VGVhbTU6NXBhc3N3b3Jk
###


POST localhost:8080/api/v1/createSheet
Authorization: Basic VGVhbTU6NXBhc3N3b3Jk
Content-Type: application/json

{
    "publisher": "Team5",
    "sheet": "Sheet1"
}
###

### ERROR: team5 createSheet w/ non-existent publisher
POST localhost:8080/api/v1/createSheet
Authorization: Basic VGVhbTU6NXBhc3N3b3Jk
Content-Type: application/json

{
    "publisher": "Team4",
    "sheet": "Sheet1"
}
###

### ERROR: team5 createSheet w/ wrong publisher
POST localhost:8080/api/v1/createSheet
Authorization: Basic VGVhbTU6NXBhc3N3b3Jk
Content-Type: application/json

{
    "publisher": "Mike",
    "sheet": "Sheet1"
}
###

### ERROR: team5 Duplicate createSheet w/ Correct Publisher team5
POST localhost:8080/api/v1/createSheet
Authorization: Basic VGVhbTU6NXBhc3N3b3Jk
Content-Type: application/json

{
    "publisher": "Team5",
    "sheet": "Sheet1"
}
###

### team5 second createSheet w/ Correct Publisher team5
POST localhost:8080/api/v1/createSheet
Authorization: Basic VGVhbTU6NXBhc3N3b3Jk
Content-Type: application/json

{
    "publisher": "Team5",
    "sheet": "Sheet2"
}
###

### Mike creates a sheet w/ correct parameters
POST localhost:8080/api/v1/createSheet
Authorization: Basic TWlrZToxMjM0NXBhc3N3b3Jk
Content-Type: application/json

{
    "publisher": "Mike",
    "sheet": "MikeSheet"
}
###

#### GET SHEETS ####

### team5 getSheets from Team5, should return sheet1 & sheet2
POST localhost:8080/api/v1/getSheets
Authorization: Basic VGVhbTU6NXBhc3N3b3Jk
Content-Type: application/json

{
    "publisher": "Team5"
}
###

### team5 getSheets from Mike, should return no sheets but proper response
POST localhost:8080/api/v1/getSheets
Authorization: Basic VGVhbTU6NXBhc3N3b3Jk
Content-Type: application/json

{
    "publisher": "Mike"
}
###

### ERROR team5 getSheets from non-existent user
POST localhost:8080/api/v1/getSheets
Authorization: Basic VGVhbTU6NXBhc3N3b3Jk
Content-Type: application/json

{
    "publisher": "Jason"
}
###

#### updatePublished, getupdates... ####

POST localhost:8080/api/v1/updatePublished
Authorization: Basic VGVhbTU6NXBhc3N3b3Jk
Content-Type: application/json

{
    "publisher": "Team5",
    "sheet": "Sheet1",
    "payload": "aaa"
}
###

###
POST localhost:8080/api/v1/getUpdatesForSubscription
Authorization: Basic VGVhbTU6NXBhc3N3b3Jk
Content-Type: application/json

{
    "publisher": "Team5",
    "sheet": "Sheet1",
    "id": "0"

}
###
POST localhost:8080/api/v1/updatePublished
Authorization: Basic VGVhbTU6NXBhc3N3b3Jk
Content-Type: application/json

{
    "publisher": "Team5",
    "sheet": "Sheet1",
    "payload": "bbb"
}
###

###
POST localhost:8080/api/v1/getUpdatesForSubscription
Authorization: Basic VGVhbTU6NXBhc3N3b3Jk
Content-Type: application/json

{
    "publisher": "Team5",
    "sheet": "Sheet1",
    "id": "0"

}
###
POST localhost:8080/api/v1/updateSubscription
Authorization: Basic VGVhbTU6NXBhc3N3b3Jk
Content-Type: application/json

{
    "publisher": "Team5",
    "sheet": "Sheet1",
    "payload": "aaa"
}
###
POST localhost:8080/api/v1/updateSubscription
Authorization: Basic VGVhbTU6NXBhc3N3b3Jk
Content-Type: application/json

{
    "publisher": "Team5",
    "sheet": "Sheet1",
    "payload": "bbb"
}
###
POST localhost:8080/api/v1/getUpdatesForPublished
Authorization: Basic VGVhbTU6NXBhc3N3b3Jk
Content-Type: application/json

{
    "publisher": "Team5",
    "sheet": "Sheet1",
    "id": "1"
}
###

### ERROR: Team5 tries to use getUpdatesForPublished on Mike's sheet
POST localhost:8080/api/v1/getUpdatesForPublished
Authorization: Basic VGVhbTU6NXBhc3N3b3Jk
Content-Type: application/json

{
    "publisher": "Mike",
    "sheet": "MikeSheet",
    "id": "0"
}
###

### ERROR: Team5 tries to check a sheet that doesn't exist
POST localhost:8080/api/v1/getUpdatesForPublished
Authorization: Basic VGVhbTU6NXBhc3N3b3Jk
Content-Type: application/json

{
    "publisher": "Team5",
    "sheet": "MikeTypeSheet",
    "id": "0"
}
###

### ERROR: Team5 tries to check updates for an id that doesn't exist
POST localhost:8080/api/v1/getUpdatesForPublished
Authorization: Basic VGVhbTU6NXBhc3N3b3Jk
Content-Type: application/json

{
    "publisher": "Team5",
    "sheet": "Sheet1",
    "id": "10"
}
###

### ERROR: Team5 tries to check updates for an id that doesn't exist
POST localhost:8080/api/v1/getUpdatesForPublished
Authorization: Basic VGVhbTU6NXBhc3N3b3Jk
Content-Type: application/json

{
    "publisher": "Team5",
    "sheet": "Sheet1",
    "id": "10"
}
###

### ERROR: Team5 tries to pass empty payload and empty sheet to updatePublished
POST localhost:8080/api/v1/updatePublished
Authorization: Basic VGVhbTU6NXBhc3N3b3Jk
Content-Type: application/json

{
    "publisher": "Team5"
}
###

### ERROR: Team5 tries to pass empty payload and empty sheet to updateSubscription
POST localhost:8080/api/v1/updatePublished
Authorization: Basic VGVhbTU6NXBhc3N3b3Jk
Content-Type: application/json

{
    "publisher": "Team5"
}
###

### ERROR: Team5 tries to pass empty payload to updatePublished
POST localhost:8080/api/v1/updatePublished
Authorization: Basic VGVhbTU6NXBhc3N3b3Jk
Content-Type: application/json

{
    "publisher": "Team5",
    "sheet": "Sheet1"
}
###

### ERROR: Team5 tries to pass empty payload to updateSubscription
POST localhost:8080/api/v1/updatePublished
Authorization: Basic VGVhbTU6NXBhc3N3b3Jk
Content-Type: application/json

{
    "publisher": "Team5",
    "sheet": "Sheet1"
}
###

### Mike successfully uses updateSubcribed to Team5's Sheet
POST localhost:8080/api/v1/updateSubscription
Authorization: Basic TWlrZToxMjM0NXBhc3N3b3Jk
Content-Type: application/json

{
    "publisher": "Team5",
    "sheet": "Sheet1",
    "payload": "$A1 51.0\n$B2 \"Bing Bong\""
}
###

### Mike successfully uses updateSubcribed to Team5's Sheet
POST localhost:8080/api/v1/updateSubscription
Authorization: Basic VGVhbTU6NXBhc3N3b3Jk
Content-Type: application/json

{
    "publisher": "Team5",
    "sheet": "Sheet1",
    "payload": "$A1 51.0\n$B2 \"Bing Bong Bang\""
}
###

### Team5 successfully uses updateSubcribed to Team5's Sheet
POST localhost:8080/api/v1/updateSubscription
Authorization: Basic VGVhbTU6NXBhc3N3b3Jk
Content-Type: application/json

{
    "publisher": "Team5",
    "sheet": "Sheet1",
    "payload": "$A1 51.0\n$B2 \"Bing Bong Bang\""
}
###

### ERROR: Team5 attempting updateSubscription with null values.
POST localhost:8080/api/v1/updateSubscription
Authorization: Basic VGVhbTU6NXBhc3N3b3Jk
Content-Type: application/json

{
    "publisher": "Team5",
    "sheet": null,
    "payload": null
}
###

### ERROR: Team5 attempting updatePublished with null values.
POST localhost:8080/api/v1/updatePublished
Authorization: Basic VGVhbTU6NXBhc3N3b3Jk
Content-Type: application/json

{
    "publisher": "Team5",
    "sheet": null,
    "payload": null
}
###

### ERROR: Team5 attempting getUpdatesForSubscription with null values.
POST localhost:8080/api/v1/getUpdatesForSubscription
Authorization: Basic VGVhbTU6NXBhc3N3b3Jk
Content-Type: application/json

{
    "publisher": "Team5",
    "sheet": null,
    "id": null
}
###

### ERROR: Team5 attempting getUpdatesForPublished with null values.
POST localhost:8080/api/v1/getUpdatesForPublished
Authorization: Basic VGVhbTU6NXBhc3N3b3Jk
Content-Type: application/json

{
    "publisher": "Team5",
    "sheet": null,
    "id": null
}
###

### ERROR: Team5 attempts to updatePublished with id instead of payload
POST localhost:8080/api/v1/updatePublished
Authorization: Basic VGVhbTU6NXBhc3N3b3Jk
Content-Type: application/json

{
    "publisher": "Team5",
    "sheet": "Sheet1",
    "id": "0"
}
###

### ERROR: Team5 attempts to updateSubscription with id instead of payload
POST localhost:8080/api/v1/updatePublished
Authorization: Basic VGVhbTU6NXBhc3N3b3Jk
Content-Type: application/json

{
    "publisher": "Team5",
    "sheet": "Sheet1",
    "id": "2"
}
###

#### DELETE SHEETS ####

### team5 deleteSheet w/ Correct Publisher Team5
POST localhost:8080/api/v1/deleteSheet
Authorization: Basic VGVhbTU6NXBhc3N3b3Jk
Content-Type: application/json

{
    "publisher": "Team5",
    "sheet": "Sheet1"
}
###

### ERROR: team5 deleteSheet w/ Correct Publisher Team5 but non-existent sheet
POST localhost:8080/api/v1/deleteSheet
Authorization: Basic VGVhbTU6NXBhc3N3b3Jk
Content-Type: application/json

{
    "publisher": "Team5",
    "sheet": "Sheet1"
}
###

### ERROR: team5 deleteSheet w/ incorrect publisher
POST localhost:8080/api/v1/deleteSheet
Authorization: Basic VGVhbTU6NXBhc3N3b3Jk
Content-Type: application/json

{
    "publisher": "Mike",
    "sheet": "Sheet1"
}
###

### ERROR: team5 deleteSheet w/ non-existent Publisher
POST localhost:8080/api/v1/deleteSheet
Authorization: Basic VGVhbTU6NXBhc3N3b3Jk
Content-Type: application/json

{
    "publisher": "Team10",
    "sheet": "Sheet1"
}
###